import { copyFile, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),".."); const srcDir=resolve(root,"src"); const distDir=resolve(root,"dist"); const source=resolve(srcDir,"navimower-map-card.js"); const target=resolve(distDir,"navimower-map-card.js");
const sourceJs=(await readdir(srcDir)).filter(n=>n.endsWith('.js')); if(sourceJs.length!==1||sourceJs[0]!=="navimower-map-card.js") throw new Error('src runtime layout invalid');
const pkg=JSON.parse(await readFile(resolve(root,'package.json'),'utf8')); let runtime=await readFile(source,'utf8');
if(pkg.version==='0.3.4-beta6'){
 const marker='// 0.3.4-beta6: schedule source selection, custom queue editing and inline settings controls.';
 if(!runtime.includes(marker)) runtime += `\n\n${marker}\n(() => {
  const Card=globalThis.customElements?.get?.('navimower-map-card'); if(!Card||Card.__navimower034Beta6Patched)return; Card.__navimower034Beta6Patched=true;
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const proto=Card.prototype; const slots=Array.from({length:12},(_,i)=>\`settings_entity_\${i+1}\`);
  const oldStub=Card.getStubConfig?.bind(Card); Card.getStubConfig=()=>({...oldStub?.(),schedule_view_mode:'auto'});
  const oldForm=Card.getConfigForm?.bind(Card); Card.getConfigForm=()=>{const f=oldForm?.()||{schema:[]};const schema=[...(f.schema||[])];schema.push({type:'expandable',name:'schedule_view',title:'Schedule button',flatten:true,schema:[{name:'schedule_view_mode',selector:{select:{options:[{value:'auto',label:'Automatic'},{value:'navimower',label:'Navimower'},{value:'native',label:'Native'}]}}}]});const label=f.computeLabel;return{...f,schema,computeLabel:i=>i?.name==='schedule_view_mode'?'Schedule view':label?.(i)||i?.name||''};};
  const discover=async card=>{if(card._beta6SchedulerEntities)return card._beta6SchedulerEntities;try{const mower=card._mowerEntity?.();const reg=await card._hass.callWS({type:'config/entity_registry/list'});const me=reg.find(e=>e.entity_id===mower);const rel=me?.device_id?reg.filter(e=>e.device_id===me.device_id&&!e.disabled_by):[];const find=(domain,suffixes)=>rel.find(e=>String(e.entity_id).startsWith(domain+'.')&&suffixes.some(s=>String(e.unique_id||'').endsWith(s)||String(e.entity_id).endsWith(s)))?.entity_id||null;card._beta6SchedulerEntities={status:find('sensor',['navimower_schedule_status']),managedSwitch:find('switch',['navimower_schedule']),nativeSwitch:find('switch',['mowing_schedule_enabled'])||card._scheduleSwitchEntity?.(),start:find('time',['navimower_schedule_start']),end:find('time',['navimower_schedule_end'])};}catch(e){console.debug('[Navimower Map Card] beta6 discovery failed',e);card._beta6SchedulerEntities={};}return card._beta6SchedulerEntities;};
  const state=(c,id)=>id?c._hass?.states?.[id]:null; const friendly=(c,id)=>state(c,id)?.attributes?.friendly_name||id; const domain=id=>String(id||'').split('.')[0];
  const call=async(c,d,s,data)=>c._hass.callService(d,s,data);
  function settingControl(c,id){const st=state(c,id),d=domain(id);if(!st)return '<div class="nm-setting-value">Unavailable</div>';if(d==='switch'||d==='input_boolean')return \`<label class="nm-inline-switch"><input type="checkbox" data-setting-switch="\${esc(id)}" \${st.state==='on'?'checked':''}><span>\${st.state==='on'?'On':'Off'}</span></label>\`;if(d==='select'||d==='input_select'){const opts=st.attributes?.options||[];return \`<select data-setting-select="\${esc(id)}">\${opts.map(o=>\`<option \${String(o)===st.state?'selected':''}>\${esc(o)}</option>\`).join('')}</select>\`;}if(d==='number'||d==='input_number'){const min=st.attributes?.min??0,max=st.attributes?.max??100,step=st.attributes?.step??1;return \`<div class="nm-number-control"><input type="range" min="\${min}" max="\${max}" step="\${step}" value="\${esc(st.state)}" data-setting-number="\${esc(id)}"><span>\${esc(st.state)}\${esc(st.attributes?.unit_of_measurement||'')}</span></div>\`;}if(d==='time'||d==='input_datetime')return \`<input type="time" value="\${esc(String(st.state).slice(0,5))}" data-setting-time="\${esc(id)}">\`;return \`<button type="button" class="nm-setting-more" data-setting-more="\${esc(id)}">\${esc(st.state)}\${st.attributes?.unit_of_measurement?' '+esc(st.attributes.unit_of_measurement):''}</button>\`;}
  function renderSettings(c){const h=c._modalHostEl;if(!h)return;const entities=slots.map(k=>c._config?.[k]).filter(Boolean);h.innerHTML=\`<div class="nm-backdrop nm-beta6-settings"><div class="nm-dialog nm-beta6-dialog"><div class="nm-schedule-dialog-head"><div class="nm-schedule-dialog-title">Settings</div><button class="nm-schedule-close" data-beta6-settings-close><ha-icon icon="mdi:close"></ha-icon></button></div><div class="nm-beta6-settings-grid">\${entities.length?entities.map(id=>\`<div class="nm-setting-row"><div class="nm-settings-name">\${esc(friendly(c,id))}</div>\${settingControl(c,id)}</div>\`).join(''):'<div class="nm-managed-empty">No settings selected in the visual editor.</div>'}</div></div></div>\`;h.querySelector('[data-beta6-settings-close]')?.addEventListener('click',()=>{c._beta6SettingsOpen=false;c._renderDialog();});h.querySelectorAll('[data-setting-switch]').forEach(x=>x.addEventListener('change',async()=>{const id=x.dataset.settingSwitch;await call(c,domain(id),x.checked?'turn_on':'turn_off',{entity_id:id});}));h.querySelectorAll('[data-setting-select]').forEach(x=>x.addEventListener('change',async()=>{const id=x.dataset.settingSelect;await call(c,domain(id),'select_option',{entity_id:id,option:x.value});}));h.querySelectorAll('[data-setting-number]').forEach(x=>x.addEventListener('change',async()=>{const id=x.dataset.settingNumber;await call(c,domain(id),'set_value',{entity_id:id,value:Number(x.value)});}));h.querySelectorAll('[data-setting-time]').forEach(x=>x.addEventListener('change',async()=>{const id=x.dataset.settingTime;const d=domain(id);await call(c,d,d==='time'?'set_value':'set_datetime',d==='time'?{entity_id:id,time:x.value}:{entity_id:id,time:x.value});}));h.querySelectorAll('[data-setting-more]').forEach(x=>x.addEventListener('click',()=>c.dispatchEvent(new CustomEvent('hass-more-info',{bubbles:true,composed:true,detail:{entityId:x.dataset.settingMore}}))));}
  function queueFrom(c,attrs){const q=Array.isArray(attrs.custom_queue)?attrs.custom_queue:[];if(q.length)return q.map(Number);return (attrs.queue||[]).filter(z=>z.status!=='completed').map(z=>Number(z.id)).filter(Number.isFinite);}
  async function saveQueue(c,queue){const id=c._mowerDeviceId?.();const data={zones:queue};if(id)data.device_id=id;await call(c,'navimower','set_schedule_queue',data);}
  function renderManaged(c){const h=c._modalHostEl;if(!h)return;const ids=c._beta6SchedulerEntities||{};const st=state(c,ids.status),a=st?.attributes||{};let queue=queueFrom(c,a);const names=new Map((a.queue||[]).map(z=>[Number(z.id),z.name||\`Zone \${z.id}\`]));const order=a.order_mode||'automatic';const editable=order==='custom';const rows=queue.map((id,i)=>\`<div class="nm-managed-zone"><span class="nm-queue-index">\${i+1}</span><span class="nm-queue-name">\${esc(names.get(id)||\`Zone \${id}\`)}</span>\${editable?\`<button data-queue-up="\${i}" title="Move up">↑</button><button data-queue-down="\${i}" title="Move down">↓</button><button data-queue-add="\${i}" title="Repeat zone">＋</button><button data-queue-remove="\${i}" title="Remove">×</button>\`:''}</div>\`).join('');h.innerHTML=\`<div class="nm-backdrop nm-managed-backdrop"><div class="nm-dialog nm-schedule-dialog"><div class="nm-schedule-dialog-head"><div class="nm-schedule-dialog-title">Navimower schedule</div><button class="nm-schedule-close" data-managed-close><ha-icon icon="mdi:close"></ha-icon></button></div><div class="nm-managed-summary"><span>\${esc(a.start||'—')}–\${esc(a.end||'—')}</span><span>\${esc(order==='custom'?'Custom order':'Automatic order')}</span><span>\${esc(st?.state||'Unavailable')}</span></div><div class="nm-managed-queue">\${rows||'<div class="nm-managed-empty">No queue available.</div>'}</div>\${editable?'<div class="nm-dialog-hint">Use arrows to reorder, + to repeat a zone, and × to remove it. Saving the queue does not enable or start the scheduler.</div>':''}</div></div>\`;h.querySelector('[data-managed-close]')?.addEventListener('click',()=>{c._beta6ManagedOpen=false;c._renderDialog();});const change=async(type,i)=>{if(type==='up'&&i>0)[queue[i-1],queue[i]]=[queue[i],queue[i-1]];if(type==='down'&&i<queue.length-1)[queue[i+1],queue[i]]=[queue[i],queue[i+1]];if(type==='add')queue.splice(i+1,0,queue[i]);if(type==='remove'&&queue.length>1)queue.splice(i,1);await saveQueue(c,queue);renderManaged(c);};for(const t of ['up','down','add','remove'])h.querySelectorAll(\`[data-queue-\${t}]\`).forEach(b=>b.addEventListener('click',()=>change(t,Number(b.dataset[\`queue\${t[0].toUpperCase()+t.slice(1)}\`]))));}
  const oldEnsure=proto._ensureDom;proto._ensureDom=function(...a){const r=oldEnsure?.apply(this,a);void discover(this);return r;};
  const oldDialog=proto._renderDialog;proto._renderDialog=function(...a){if(this._beta6SettingsOpen){renderSettings(this);return;}if(this._beta6ManagedOpen){renderManaged(this);return;}return oldDialog?.apply(this,a);};
  const oldOpen=proto._openScheduleDialog;proto._openScheduleDialog=async function(...a){const ids=await discover(this);const mode=this._config?.schedule_view_mode||'auto';const managedOn=state(this,ids.managedSwitch)?.state==='on';this._beta6SettingsOpen=false;if(mode==='navimower'||(mode==='auto'&&managedOn&&ids.status)){this._beta5ManagedScheduleOpen=false;this._scheduleDialogOpen=false;this._mowDialogOpen=false;this._beta6ManagedOpen=true;this._renderDialog();return;}this._beta6ManagedOpen=false;return oldOpen?.apply(this,a);};
  const oldHass=Object.getOwnPropertyDescriptor(proto,'hass');if(oldHass?.set)Object.defineProperty(proto,'hass',{configurable:true,get:oldHass.get,set(v){oldHass.set.call(this,v);if(this._beta6SettingsOpen)renderSettings(this);if(this._beta6ManagedOpen)renderManaged(this);}});
  const oldEnsure2=proto._ensureDom;proto._ensureDom=function(...a){const r=oldEnsure2?.apply(this,a);const gear=this.querySelector?.('.nm-settings-button');if(gear&&!gear.__beta6){gear.__beta6=true;gear.addEventListener('click',()=>{this._beta5SettingsOpen=false;this._beta6ManagedOpen=false;this._beta6SettingsOpen=true;this._renderDialog();},{capture:true});}return r;};
  console.info('[Navimower Map Card] 0.3.4-beta6 schedule source, custom queue and inline settings enabled');
})();\n`;
 await writeFile(source,runtime,'utf8');
 let ch=await readFile(resolve(root,'CHANGELOG.md'),'utf8');if(!ch.includes('## 0.3.4-beta6 - 2026-08-25'))ch=ch.replace('# Changelog\n\n','# Changelog\n\n## 0.3.4-beta6 - 2026-08-25\n\n### Added\n\n- Add Visual Editor Schedule view selection: Automatic, Navimower or Native. Navimower can be opened while disabled so Custom order can be prepared safely.\n- Add Custom queue editing with reorder, repeat and remove controls backed by `navimower.set_schedule_queue`.\n- Render switch, select, number and time entities as direct controls in the Settings dialog; read-only/other entities retain More Info.\n\n');await writeFile(resolve(root,'CHANGELOG.md'),ch,'utf8');
}
await rm(distDir,{recursive:true,force:true});await mkdir(distDir,{recursive:true});await copyFile(source,target);console.log(`Built ${target}`);
